# Staging environment values
replicaCount: 2

image:
  tag: "staging"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  hosts:
    - host: vhr-staging.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vhr-frontend-staging-tls
      hosts:
        - vhr-staging.example.com

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
