# Production environment values
replicaCount: 3

image:
  tag: "prod"

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  hosts:
    - host: vhr.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vhr-frontend-prod-tls
      hosts:
        - vhr.example.com

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

rollout:
  enabled: true
  strategy: canary
  canary:
    steps:
      - setWeight: 1
      - pause: { duration: 5m }
      - setWeight: 5
      - pause: { duration: 5m }
      - setWeight: 20
      - pause: { duration: 5m }
      - setWeight: 40
      - pause: { duration: 5m }
      - setWeight: 60
      - pause: { duration: 5m }
      - setWeight: 80
      - pause: { duration: 5m }
    analysis:
      enabled: true

istio:
  enabled: true
  host: vhr.example.com
